### ISSUE TITLE
java.lang.UnsupportedOperationException: This feature requires ASM6

### ISSUE THREAD

**Issue by Wccczy** [SusionSuc/rabbit-client#15]
请大老赐教，是不是gradle或者java version问题，import了rabbit 库之后编译不过

**Comment by Wccczy** [comment]
log:
Caused by: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: java.lang.UnsupportedOperationException: This feature requires ASM6
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at com.susion.rabbit.gradle.core.context.RabbitTransformInvocation.doFullTransform$rabbit_gradle_transform(RabbitTransformInvocation.kt:128)
at com.susion.rabbit.gradle.RabbitFirstTransform.transform(RabbitFirstTransform.kt:66)

**Comment by SusionSuc** [comment]
你的工程的gradle版本是多少？

**Comment by TangHuaiZhe** [comment]
我在另一个ASM相关的项目中也遇到了这个问题，参考[Update to ASM6 and Fix #32](https://github.com/Leaking/Hunter/pull/33), 简单把ASM5升级到ASM6可以解决这个问题, @SusionSuc 这个ASM的升级会有副作用吗？

**Comment by SusionSuc** [comment]
谢谢，我看一下这个升级有没有问题，没有我会尽快fix

**Comment by SusionSuc** [comment]
@Wccczy  可以升级到alpha15试一下
